export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Title } from './Title'
export { default as Projects } from './Projects'
export { default as Certificates } from './Certificates'
export { default as Footer } from './Footer'